package httpapi

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/open-shield/open-shield/engine/internal/rules"
	"github.com/open-shield/open-shield/internal/audit"
	"github.com/open-shield/open-shield/internal/model"
	"github.com/open-shield/open-shield/test/corpus"
)

// This server is the contract between proxy/lua/openshield.lua and the rules
// engine: the Lua hook posts a decideRequest and acts on the decideResponse.
// Nothing else in the system sits on the request path, so a change here that
// nobody notices is a change to what the proxy does with live traffic.
//
// Every test drives the real router, not the handler functions directly, so
// method and path routing are covered along with the bodies.

// --- Harness -----------------------------------------------------------------

type harness struct {
	server *httptest.Server
	repo   *audit.Memory
	writer *audit.Writer
	engine *rules.Engine
}

// newHarness wires a server over the real signature set and an in-memory log.
// ready defaults to healthy; pass a non-nil error to simulate a dependency
// being down.
func newHarness(t *testing.T, chain []rules.Rule, ready func() error) *harness {
	t.Helper()

	repo := audit.NewMemory()
	writer, err := audit.NewWriter(context.Background(), repo, audit.WriterOptions{Buffer: 256})
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}

	if chain == nil {
		set, err := rules.LoadSignatures("")
		if err != nil {
			t.Fatalf("LoadSignatures: %v", err)
		}
		chain = []rules.Rule{
			rules.NewPatternRule("sqli", set.SQLi, 8192),
			rules.NewPatternRule("xss", set.XSS, 8192),
		}
	}
	engine := rules.New(chain)

	srv := httptest.NewServer(New(Options{
		Engine:  engine,
		Writer:  writer,
		Ready:   ready,
		Version: "test",
	}).Handler())
	t.Cleanup(srv.Close)
	// Close is idempotent, so a test that already drained through entries() is
	// unaffected; this only stops the append goroutine leaking from the rest.
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = writer.Close(ctx)
	})

	return &harness{server: srv, repo: repo, writer: writer, engine: engine}
}

// decide posts a decision request and returns the parsed verdict.
func (h *harness) decide(t *testing.T, body any) (int, decideResponse) {
	t.Helper()

	var raw []byte
	switch v := body.(type) {
	case string:
		raw = []byte(v)
	default:
		var err error
		if raw, err = json.Marshal(v); err != nil {
			t.Fatalf("marshal request: %v", err)
		}
	}

	resp, err := http.Post(h.server.URL+"/v1/decide", "application/json", strings.NewReader(string(raw)))
	if err != nil {
		t.Fatalf("POST /v1/decide: %v", err)
	}
	defer resp.Body.Close()

	var out decideResponse
	if resp.StatusCode == http.StatusOK {
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			t.Fatalf("decode response: %v", err)
		}
	} else {
		_, _ = io.Copy(io.Discard, resp.Body)
	}
	return resp.StatusCode, out
}

// entries flushes the writer and returns everything that reached the log. The
// append path is asynchronous by design (§8.2), so a test that reads the store
// without draining first is reading a race.
func (h *harness) entries(t *testing.T) []model.AuditEntry {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := h.writer.Close(ctx); err != nil {
		t.Fatalf("writer.Close: %v", err)
	}
	return h.repo.Entries()
}

// stubRule answers a fixed verdict, and optionally asks for its own status.
type stubRule struct {
	name    string
	verdict model.Verdict
	status  int
}

func (s stubRule) Name() string { return s.name }

func (s stubRule) Evaluate(context.Context, *model.RequestContext) (model.Verdict, string) {
	return s.verdict, s.name + " matched"
}

func (s stubRule) BlockStatus() int { return s.status }

// --- The verdict ------------------------------------------------------------

func TestDecideAllowsOrdinaryTraffic(t *testing.T) {
	h := newHarness(t, nil, nil)

	status, resp := h.decide(t, map[string]any{
		"request_id": "req-allow",
		"ip":         "203.0.113.7",
		"method":     "GET",
		"path":       "/catalogo",
		"query":      "page=2",
	})

	if status != http.StatusOK {
		t.Fatalf("status = %d, want 200", status)
	}
	if resp.Verdict != model.Allow {
		t.Fatalf("verdict = %q, want allow", resp.Verdict)
	}
	if resp.Rule != "" || resp.Reason != "" {
		t.Errorf("an allow must attribute nothing, got rule=%q reason=%q", resp.Rule, resp.Reason)
	}
}

func TestDecideEchoesTheRequestID(t *testing.T) {
	h := newHarness(t, nil, nil)

	// The X-Request-ID generated by the proxy travels to the engine, into the
	// audit entry and on to the backend. It is what makes one request
	// followable across all three layers, so the engine must hand it back
	// unchanged even on the paths where it has nothing else to say.
	const id = "8f14e45f-ea56-4c7b-9b1a-2d3c4e5f6a7b"

	_, resp := h.decide(t, map[string]any{"request_id": id, "ip": "203.0.113.7", "path": "/"})
	if resp.RequestID != id {
		t.Fatalf("request_id = %q, want %q", resp.RequestID, id)
	}

	for _, entry := range h.entries(t) {
		if entry.RequestID != id {
			t.Fatalf("audit entry request_id = %q, want %q", entry.RequestID, id)
		}
	}
}

func TestDecideBlocksWithTheRuleThatMatched(t *testing.T) {
	h := newHarness(t, nil, nil)

	status, resp := h.decide(t, map[string]any{
		"request_id": "req-sqli",
		"ip":         "203.0.113.7",
		"method":     "GET",
		"path":       "/productos",
		"query":      "id=1%27%20OR%20%271%27%3D%271",
	})

	if status != http.StatusOK {
		t.Fatalf("status = %d, want 200 — the verdict travels in the body, not the status", status)
	}
	if resp.Verdict != model.Block {
		t.Fatalf("verdict = %q, want block", resp.Verdict)
	}
	if resp.Rule != "sqli" {
		t.Errorf("rule = %q, want sqli", resp.Rule)
	}
	if resp.Status != http.StatusForbidden {
		t.Errorf("status = %d, want 403", resp.Status)
	}
}

// A rate-limited client gets 429, not 403. The distinction is not cosmetic: a
// correct client reads 429 as "retry later" and 403 as "give up", and the proxy
// only knows which to send because the engine tells it.
func TestDecideCarriesTheRuleSpecificBlockStatus(t *testing.T) {
	h := newHarness(t, []rules.Rule{
		stubRule{name: "ratelimit", verdict: model.Block, status: http.StatusTooManyRequests},
	}, nil)

	_, resp := h.decide(t, map[string]any{"request_id": "req-429", "ip": "203.0.113.7", "path": "/"})

	if resp.Status != http.StatusTooManyRequests {
		t.Fatalf("status = %d, want 429", resp.Status)
	}
	if resp.Rule != "ratelimit" {
		t.Fatalf("rule = %q, want ratelimit", resp.Rule)
	}
}

func TestDecideReportsItsOwnLatency(t *testing.T) {
	h := newHarness(t, nil, nil)

	_, resp := h.decide(t, map[string]any{"request_id": "req-ms", "ip": "203.0.113.7", "path": "/"})

	// §6.1 asks for per-stage latency in the audit record, and §8.2 budgets the
	// whole added path under 50 ms. A chain evaluation that reports zero is
	// measuring nothing.
	if resp.DecisionMS <= 0 {
		t.Fatalf("decision_ms = %v, want a positive measurement", resp.DecisionMS)
	}
	if resp.DecisionMS > 50 {
		t.Errorf("decision_ms = %v ms for a trivial request; §8.2 budgets 50 ms for the whole path", resp.DecisionMS)
	}
}

func TestDecideRejectsAMalformedBody(t *testing.T) {
	h := newHarness(t, nil, nil)

	// The proxy is the only caller. A malformed body means the two are out of
	// step, and 400 makes the proxy fall back to OS_FAIL_MODE rather than
	// guessing what the engine meant.
	status, _ := h.decide(t, `{"request_id": "req-bad", `)
	if status != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", status)
	}
}

func TestDecideRejectsAnOversizedBody(t *testing.T) {
	h := newHarness(t, nil, nil)

	// The proxy already truncates at OS_MAX_BODY_INSPECT_BYTES; this is the
	// engine's own guard against a caller that is not the proxy.
	status, _ := h.decide(t, map[string]any{
		"request_id": "req-huge",
		"ip":         "203.0.113.7",
		"path":       "/",
		"body":       strings.Repeat("A", 2<<20),
	})
	if status != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400 for a body over %d bytes", status, maxDecideBody)
	}
}

func TestDecideLowercasesHeaderNames(t *testing.T) {
	h := newHarness(t, nil, nil)

	// The Lua hook lowercases before sending, but RequestContext.Header does an
	// exact lookup, so a caller that does not would silently bypass every
	// header-based rule.
	_, resp := h.decide(t, map[string]any{
		"request_id": "req-headers",
		"ip":         "203.0.113.7",
		"path":       "/",
		"headers":    map[string]string{"Referer": "http://x.test/?q=<script>alert(1)</script>"},
	})

	if resp.Verdict != model.Block || resp.Rule != "xss" {
		t.Fatalf("verdict=%q rule=%q, want a block by xss on the Referer header", resp.Verdict, resp.Rule)
	}
}

// --- What reaches the audit log ---------------------------------------------

// The whole corpus is replayed through the HTTP surface, not just the rule
// chain, because the payload the log ends up with is built here.
func TestDecideRecordsEveryDecision(t *testing.T) {
	h := newHarness(t, nil, nil)

	cases := append(append([]corpus.Case{}, corpus.Attacks()...), corpus.Benign()...)
	for _, c := range cases {
		_, resp := h.decide(t, decideRequest{
			RequestID: c.ID,
			IP:        "203.0.113.7",
			Method:    c.HTTPMethod(),
			Path:      c.Path,
			Query:     c.Query,
			Host:      "ejemplo.test",
			Headers:   c.Headers,
			Body:      c.Body,
		})

		want := model.Block
		if c.Rule == "" {
			want = model.Allow
		}
		if resp.Verdict != want {
			t.Errorf("%s: verdict = %q, want %q", c.ID, resp.Verdict, want)
		}
	}

	entries := h.entries(t)
	if len(entries) != len(cases) {
		t.Fatalf("recorded %d entries for %d decisions — every decision goes on the record (RF-06)",
			len(entries), len(cases))
	}
	for _, entry := range entries {
		if entry.Kind != model.KindTraffic {
			t.Errorf("%s: kind = %q, want %q", entry.RequestID, entry.Kind, model.KindTraffic)
		}
	}
}

// TestAuditPayloadNeverCarriesTheBodyOrCredentials is the negative invariant of
// §6: the request body is inspected and then discarded, and the Cookie and
// Authorization headers never reach the store. An append-only log with long
// retention is the worst possible place for the passwords, tokens and personal
// data a POST carries — a log that keeps them is a credential store.
func TestAuditPayloadNeverCarriesTheBodyOrCredentials(t *testing.T) {
	h := newHarness(t, nil, nil)

	const (
		secretBody   = "usuario=maria&clave=SuperSecreto123"
		sessionToken = "session=abcdef0123456789"
		bearer       = "Bearer eyJhbGciOiJIUzI1NiJ9.payload.signature"
	)

	h.decide(t, decideRequest{
		RequestID: "req-secrets",
		IP:        "203.0.113.7",
		Method:    "POST",
		Path:      "/login",
		Host:      "ejemplo.test",
		Headers: map[string]string{
			"cookie":        sessionToken,
			"authorization": bearer,
			"user-agent":    "Mozilla/5.0",
		},
		Body: secretBody,
	})

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}

	// Serialise the whole payload and search it: checking individual keys would
	// miss a secret that a future change tucks into a nested field.
	raw, err := json.Marshal(entries[0].Payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}
	recorded := string(raw)

	for name, forbidden := range map[string]string{
		"the request body":          secretBody,
		"the password from it":      "SuperSecreto123",
		"the Cookie header":         sessionToken,
		"the Authorization header":  bearer,
		"the bearer token contents": "eyJhbGciOiJIUzI1NiJ9",
	} {
		if strings.Contains(recorded, forbidden) {
			t.Errorf("the audit payload contains %s\n  payload: %s", name, recorded)
		}
	}

	// What must survive: enough to identify the client and the request.
	headers, ok := entries[0].Payload["headers"].(map[string]any)
	if !ok {
		t.Fatalf("payload has no headers map: %s", recorded)
	}
	if headers["user-agent"] != "Mozilla/5.0" {
		t.Errorf("user-agent = %v, want it kept — it identifies the client", headers["user-agent"])
	}
	if _, present := headers["cookie"]; present {
		t.Error("the cookie header survived into the audit payload")
	}
	if _, present := headers["authorization"]; present {
		t.Error("the authorization header survived into the audit payload")
	}
}

// A block is only useful as evidence if the log says why. What is kept is the
// bounded excerpt around the match — the reason — and nothing more of the
// payload than that.
func TestAuditPayloadKeepsTheEvidenceForABlock(t *testing.T) {
	h := newHarness(t, nil, nil)

	h.decide(t, decideRequest{
		RequestID: "req-evidence",
		IP:        "198.51.100.4",
		Method:    "GET",
		Path:      "/buscar",
		Query:     "q=x%27%20UNION%20SELECT%20clave%20FROM%20usuarios--",
		Host:      "ejemplo.test",
	})

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}
	payload := entries[0].Payload

	for key, want := range map[string]any{
		"verdict": string(model.Block),
		"rule":    "sqli",
		"ip":      "198.51.100.4",
		"method":  "GET",
		"path":    "/buscar",
		"host":    "ejemplo.test",
	} {
		if got := fmt.Sprint(payload[key]); got != want {
			t.Errorf("payload[%q] = %q, want %q", key, got, want)
		}
	}

	reason, _ := payload["reason"].(string)
	if !strings.Contains(reason, "union_select") {
		t.Errorf("reason = %q, want it to name the signature that fired", reason)
	}
	if len(reason) > 512 {
		t.Errorf("reason is %d bytes; it is attacker-controlled input and must stay bounded", len(reason))
	}
}

func TestAuditPayloadOmitsRuleFieldsOnAnAllow(t *testing.T) {
	h := newHarness(t, nil, nil)

	h.decide(t, decideRequest{RequestID: "req-clean", IP: "203.0.113.7", Method: "GET", Path: "/"})

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}
	for _, key := range []string{"rule", "reason", "status"} {
		if _, present := entries[0].Payload[key]; present {
			t.Errorf("payload carries %q on an allow; nothing blocked, so there is nothing to attribute", key)
		}
	}
}

func TestAuditPayloadMarksATruncatedBody(t *testing.T) {
	h := newHarness(t, nil, nil)

	// A body the proxy had to cut is partially unknown, not clean. The flag is
	// what lets an operator tell "nothing matched" from "nothing matched in the
	// part we could see".
	h.decide(t, decideRequest{
		RequestID:     "req-truncated",
		IP:            "203.0.113.7",
		Path:          "/subida",
		Body:          strings.Repeat("a", 100),
		BodyTruncated: true,
	})

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}
	if entries[0].Payload["body_truncated"] != true {
		t.Errorf("body_truncated = %v, want true", entries[0].Payload["body_truncated"])
	}
}

func TestAuditPayloadBoundsAnAbsurdPath(t *testing.T) {
	h := newHarness(t, nil, nil)

	h.decide(t, decideRequest{
		RequestID: "req-long",
		IP:        "203.0.113.7",
		Path:      "/" + strings.Repeat("a", 8000),
		Query:     strings.Repeat("b", 8000),
	})

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}
	for _, key := range []string{"path", "query"} {
		value, _ := entries[0].Payload[key].(string)
		// truncate appends an ellipsis, so the cap is 2048 plus its bytes.
		if len(value) > 2048+len("…") {
			t.Errorf("payload[%q] is %d bytes; the log must not grow with the request", key, len(value))
		}
	}
}

// --- The dashboard's synchronous append -------------------------------------

func TestAuditEndpointRecordsAnAdministrativeChange(t *testing.T) {
	h := newHarness(t, nil, nil)

	status, _ := postAudit(t, h, auditRequest{
		Kind:      model.KindAdmin,
		RequestID: "admin-1",
		Payload:   map[string]any{"actor": "admin", "action": "rule.disable", "rule": "xss"},
	})
	if status != http.StatusCreated {
		t.Fatalf("status = %d, want 201", status)
	}

	entries := h.entries(t)
	if len(entries) != 1 {
		t.Fatalf("recorded %d entries, want 1", len(entries))
	}
	if entries[0].Kind != model.KindAdmin {
		t.Errorf("kind = %q, want %q", entries[0].Kind, model.KindAdmin)
	}
}

// 'traffic' is reserved for the decision path. Without this, anything that can
// reach the engine could plant an entry claiming a request was blocked when it
// never happened — and it would verify, because it would be properly chained.
func TestAuditEndpointRefusesToForgeTrafficEntries(t *testing.T) {
	h := newHarness(t, nil, nil)

	for _, kind := range []string{model.KindTraffic, "", "invented"} {
		status, _ := postAudit(t, h, auditRequest{Kind: kind, RequestID: "forged"})
		if status != http.StatusBadRequest {
			t.Errorf("kind %q accepted with status %d, want 400", kind, status)
		}
	}

	if entries := h.entries(t); len(entries) != 0 {
		t.Fatalf("recorded %d entries, want none", len(entries))
	}
}

// When the entry cannot be committed the endpoint answers 503, and the
// dashboard refuses the change. An unaudited change to what the proxy blocks is
// worse than a change that could not be made.
func TestAuditEndpointReportsAFailedAppend(t *testing.T) {
	repo := &failingRepo{Memory: audit.NewMemory()}
	writer, err := audit.NewWriter(context.Background(), repo, audit.WriterOptions{Buffer: 8})
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = writer.Close(ctx)
	})

	srv := httptest.NewServer(New(Options{
		Engine: rules.New(nil),
		Writer: writer,
	}).Handler())
	t.Cleanup(srv.Close)

	repo.fail.Store(true)

	body, _ := json.Marshal(auditRequest{Kind: model.KindAdmin, RequestID: "admin-2"})
	resp, err := http.Post(srv.URL+"/v1/audit", "application/json", strings.NewReader(string(body)))
	if err != nil {
		t.Fatalf("POST /v1/audit: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want 503", resp.StatusCode)
	}
}

func TestAuditEndpointRejectsAMalformedBody(t *testing.T) {
	h := newHarness(t, nil, nil)

	resp, err := http.Post(h.server.URL+"/v1/audit", "application/json", strings.NewReader("{nope"))
	if err != nil {
		t.Fatalf("POST /v1/audit: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", resp.StatusCode)
	}
}

func postAudit(t *testing.T, h *harness, req auditRequest) (int, string) {
	t.Helper()

	body, err := json.Marshal(req)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	resp, err := http.Post(h.server.URL+"/v1/audit", "application/json", strings.NewReader(string(body)))
	if err != nil {
		t.Fatalf("POST /v1/audit: %v", err)
	}
	defer resp.Body.Close()

	out, _ := io.ReadAll(resp.Body)
	return resp.StatusCode, string(out)
}

// failingRepo is an in-memory log whose appends can be switched to failing, to
// exercise the paths where the store is unreachable.
type failingRepo struct {
	*audit.Memory
	fail atomic.Bool
}

func (r *failingRepo) Append(ctx context.Context, entry model.AuditEntry) error {
	if r.fail.Load() {
		return errors.New("audit store unavailable")
	}
	return r.Memory.Append(ctx, entry)
}

// --- Health, readiness and status -------------------------------------------

func TestHealthIsAlwaysAvailable(t *testing.T) {
	h := newHarness(t, nil, func() error { return errors.New("database down") })

	// Liveness answers whether the process is running, readiness whether it can
	// do its job. Conflating them makes an orchestrator restart a healthy
	// engine because its database blinked.
	if status, _ := get(t, h.server.URL+"/healthz"); status != http.StatusOK {
		t.Fatalf("/healthz = %d, want 200 even with a failing dependency", status)
	}
}

func TestReadyReportsAFailingDependency(t *testing.T) {
	h := newHarness(t, nil, func() error { return errors.New("database down") })

	// Compose waits on /readyz before starting the proxy, so this is what keeps
	// traffic away from an engine that cannot record what it decides.
	status, body := get(t, h.server.URL+"/readyz")
	if status != http.StatusServiceUnavailable {
		t.Fatalf("/readyz = %d, want 503", status)
	}
	if !strings.Contains(body, "database down") {
		t.Errorf("/readyz body = %q, want the underlying error", body)
	}
}

func TestReadyIsOKByDefault(t *testing.T) {
	h := newHarness(t, nil, nil)

	if status, _ := get(t, h.server.URL+"/readyz"); status != http.StatusOK {
		t.Fatalf("/readyz = %d, want 200", status)
	}
}

// The dashboard shows this so that "the rate limit is silently not running" is
// something an operator sees, rather than something they discover after an
// incident.
func TestStatusReportsTheChainAndTheQueue(t *testing.T) {
	h := newHarness(t, nil, nil)
	h.engine.SetEnabled(map[string]bool{"sqli": true, "xss": false})

	status, body := get(t, h.server.URL+"/v1/status")
	if status != http.StatusOK {
		t.Fatalf("/v1/status = %d, want 200", status)
	}

	var out struct {
		Version string          `json:"version"`
		Chain   []string        `json:"chain"`
		Enabled map[string]bool `json:"enabled"`
		Audit   struct {
			Dropped  int64 `json:"dropped"`
			Capacity int   `json:"capacity"`
		} `json:"audit"`
	}
	if err := json.Unmarshal([]byte(body), &out); err != nil {
		t.Fatalf("decode status: %v — body was %s", err, body)
	}

	if out.Version != "test" {
		t.Errorf("version = %q, want %q", out.Version, "test")
	}
	if len(out.Chain) != 2 || out.Chain[0] != "sqli" {
		t.Errorf("chain = %v, want it in evaluation order", out.Chain)
	}
	if out.Enabled["xss"] {
		t.Error("enabled[xss] = true after it was switched off")
	}
	// The dropped counter is the only warning that the log is losing entries
	// under load, so it has to be reachable from outside the process.
	if out.Audit.Capacity != 256 {
		t.Errorf("audit.capacity = %d, want the configured buffer", out.Audit.Capacity)
	}
}

func TestRoutingRejectsTheWrongMethod(t *testing.T) {
	h := newHarness(t, nil, nil)

	// /v1/decide is registered for POST only. A GET reaching it would mean the
	// router is looser than the contract says.
	status, _ := get(t, h.server.URL+"/v1/decide")
	if status != http.StatusMethodNotAllowed {
		t.Fatalf("GET /v1/decide = %d, want 405", status)
	}
}

func get(t *testing.T, url string) (int, string) {
	t.Helper()

	resp, err := http.Get(url)
	if err != nil {
		t.Fatalf("GET %s: %v", url, err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	return resp.StatusCode, string(body)
}
